### ISSUE TITLE
Allow customization of file names when uploading to S3

### ISSUE THREAD

**Issue by MalikBagwala** [payloadcms/plugin-cloud-storage#12]
@jmikrut is there any way I can customize a filename when uploading
eg. `my_file.jpg` -> `ceEV8Qcx.jp` (or any other name), this will allow for more consistent file names.

**Comment by jmikrut** [comment]
Hey @MalikBagwala — yes, you can do this by passing in your own `filename` field, with a `beforeValidate` hook that can set a filename accordingly. You could also change the incoming `file` data on the `req` in a `beforeOperation` hook, so that the changes you make to the `req.file.name` are then propagated through the remainder of the auto-generated image sizes. 

Does this help?

**Comment by MalikBagwala** [comment]
This did the trick @jmikrut
