### ISSUE TITLE
Adding cacheControl headers

### ISSUE THREAD

**Issue by JulianAtTheFrontend** [payloadcms/plugin-cloud-storage#26]
Is it possible to add headers like `CacheControl: 'max-age=31536000'`?

**Comment by jmikrut** [comment]
Hey @JulianAtTheFrontend — yes you can, depending on a few things.

By default, you will be "reading" files from Payload directly, which streams the files through your CMS and then to your users. In this case, you'd just add Express middleware to your `collection.upload.handlers`, which would be responsible for adding the cache control header. You'd just do it the typical Express way there.

But, if you are using `disablePayloadAccessControl: true`, then you would need to your cloud storage vendor to take care of adding the headers for you. 

Here's a StackOverflow link for how to do this on S3:
https://stackoverflow.com/questions/22501465/how-to-add-cache-control-in-aws-s3

This should do it! I will convert this to a Discussion so that others can find it if they are interested.
